from sys import argv
from flask import Flask, request
import os

# TODO: Since this application uses os and exec, it is very unsafe.
# It will be important to look into the safety concerns this brings up before
# this application goes into the hands of the public.

app = Flask(__name__)

# This code should be included in all code generated by our model
# It overrides print to write to a file that our Flask server can read from
# to obtain the results of the code.
#
# TODO: Change my_print to a large hash value so that we don't have to worry about
#       generated code making a function called my_print. We might be able to achieve
#       the same thing using modules but idk
# TODO: Fix the issue where someone calls print with a variable number of arguments.
base_code = \
'''
def my_print(print_arg):
    with open('python_code_output.txt', 'a') as f:
        f.write(str(print_arg))
        f.write('\\n')
print = my_print
'''

@app.route('/', methods=['POST'])
def index():
    my_pseudocode = request.get_json()['code']
    my_python_code = translate_pseudocode_to_python(my_pseudocode)
    
    result = execute_python(my_python_code)
    
    os.remove('python_code_output.txt') # cleanup
    
    return result

# Description: Takes a string of @pseudocode and outputs a properly formatted string of python
# Params:
#    @pseudocode
#        -> Type: String
#        -> Format: No hard format requirements! (as that's kinda the point of the project lol)
def translate_pseudocode_to_python(pseudocode):
    return pseudocode # TODO: Actually implement translation rather than returning input

# Description: execute_python will execute @python_code and return anything printed by @python_code
# Params:
#   @python_code
#       -> Type: String
#       -> Format: Should conform to standard formatting rules of python (i.e. include tabs/newlines)
def execute_python(python_code):    
    exec(base_code + python_code)
    return open('python_code_output.txt', 'r').read()

if __name__ == '__main__':
    app.run(debug=True, port=5000)